//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VhnK22CNT4Lesson11_2210900050.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VhnCategory
    {
        public int VhnID { get; set; }
        public string VhnCateName { get; set; }
        public Nullable<bool> VhnStatus { get; set; }
    }
}
