//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VhnK22CNT4Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VhnAccount
    {
        public int VhnID { get; set; }
        public string VhnUserName { get; set; }
        public string VhnPassword { get; set; }
        public string VhnFullName { get; set; }
        public string VhnEmail { get; set; }
        public string VhnPhone { get; set; }
        public Nullable<bool> VhnActive { get; set; }
    }
}
