//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VhnBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vhnKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vhnKhoa()
        {
            this.vhnSinhVien = new HashSet<vhnSinhVien>();
        }
    
        public string VhnMaKH { get; set; }
        public string VhnTenKH { get; set; }
        public Nullable<bool> VhnTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vhnSinhVien> vhnSinhVien { get; set; }
    }
}
