//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VhnBaiKiemTraGK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VhnK22CNT4lesson07DbEntities : DbContext
    {
        public VhnK22CNT4lesson07DbEntities()
            : base("name=VhnK22CNT4lesson07DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vhnKhoa> vhnKhoa { get; set; }
        public virtual DbSet<vhnSinhVien> vhnSinhVien { get; set; }
    }
}
