//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VhnBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vhnSinhVien
    {
        public string VhnMaSV { get; set; }
        public string VhnHoSV { get; set; }
        public string VhnTenSV { get; set; }
        public Nullable<System.DateTime> VhnNgaySinh { get; set; }
        public Nullable<bool> VhnPhai { get; set; }
        public string VhnPhone { get; set; }
        public string VhnEmail { get; set; }
        public string VhnMaKH { get; set; }
    
        public virtual vhnKhoa vhnKhoa { get; set; }
    }
}
